
default: &default
  adapter: postgresql
  encoding: utf-8
  username: fruityfree
  password: unilever
  pool: 5

development:
  <<: *default
  database: pomodoro_development

test:
  <<: *default
  database: pomodoro_test

production:
  <<: *default
  database: pomodoro_production


# default: &default
#   adapter: sqlite3
#   pool: 5
#   timeout: 5000

# development:
#   <<: *default
#   database: db/development.sqlite3

# test:
#   <<: *default
#   database: db/test.sqlite3

# production:
#   <<: *default
#   database: db/production.sqlite3
